### ISSUE TITLE
【優先度高】SQLシステムの実装

### ISSUE THREAD

**Issue by kumitatepazuru** [inudevtech/metaverseplugin#1]
SQLコネクションはオーバーヘッドを減らすためプラグイン有効時に接続、pingで通信維持をして無効時に切断という形にする。
util.Sqlみたいな名前のクラスに実装してく。
class初期化部分に接続の処理、`void disconnect`関数で切断の処理を書く。
Sqlコネクションデータはconfig.ymlに保管しておき、接続時に取得する形にする。
↓参考コード
https://github.com/arainu-github/metaverseplugin/blob/develop/src/main/java/world/arainu/core/metaverseplugin/utils/sqlUtil.java

**Comment by tererun** [comment]
実装予定のデータベースはMySQLですか？

**Comment by kumitatepazuru** [comment]
そうですね。犬開発内の既存のMySQLサーバーを使用する予定です。

**Comment by kumitatepazuru** [comment]
depend on #4
