### ISSUE TITLE
物価の概念を作る

### ISSUE THREAD

**Issue by kumitatepazuru** [inudevtech/metaverseplugin#10]
後でものとお金を取引できるようにする予定なので、ものの値段を決める価格の変化の概念を追加する。
一旦は各鉱石（石炭・鉄・銅・金・ラピスラズリ・レッドストーン・ダイヤモンド）だけの実装にする。
これから増えていくことも考えられるので、config.ymlですべて追加・調整ができるようにする。
config.ymlには以下のように記載していく感じにする。
```yaml
prices:
  iron: 1000
  diamond: 100000
```

価格の変化は`1000/販売個数+基本の値段`
基本の値段はyamlに記載されているもの、販売個数はSQL上で管理する。
SQLはテーブル名`price`で以下のように記載していく。
| type:VARCHAR(100)    | count:INT  | 
| ------- | ------ | 
| diamond | 1000   | 
| iron    | 5400   | 
| coal    | 120000 | 

販売個数は以下のように増減できるようにする。
```java
price.addPrice("diamond",1000) //ダイヤモンドの販売個数を1000増やす
price.subtractPrice("diamond", 1000) //ダイヤモンドの販売個数を1000減らす
```

**Comment by toru-toruto** [comment]
config.ymlを編集したときって、サーバを再起動するものなんですかね？
それとも、起動したまま変更を反映する手段があったりしますか？

**Comment by kumitatepazuru** [comment]
今のところは鯖再起or`reload confirm`ですね（）
後々そこら辺のリロードコマンドも作りたいところ。

**Comment by toru-toruto** [comment]
なるほどコマンドか、ありがとうございます。

**Comment by kumitatepazuru** [comment]
自分の構想にとんでもないミスがあったので一旦このissueは保留。
とるとさんにはせっかく作っていただいたのに申し訳ないがPRも保留とする。
新しいissueを建ててそちらに新しい概念を書いていく。
