### ISSUE TITLE
SQLのシンタックスがおかしい

### ISSUE THREAD

**Issue by kumitatepazuru** [inudevtech/metaverseplugin#102]
### バグの内容

https://github.com/Profundus-inudev/Profundus/blob/develop/src/main/java/tech/inudev/profundus/database/DBUUser.java#L91
ここで[こんなエラー](https://github.com/Profundus-inudev/Profundus/pull/99#pullrequestreview-1083408289) が発生する
確認したところ@kidocchyさんが書いたコードっぽいのですがlibへのPRのレビューも含め、修正お願いできますか？

### マインクラフトのバージョン

1.18.2(Java版)

**Comment by kidocchy** [comment]
少々お待ちください〜〜
