### ISSUE TITLE
【優先度高】moneyクラスにSQLの処理を実装する

### ISSUE THREAD

**Issue by kumitatepazuru** [inudevtech/metaverseplugin#11]
depends on #2 
init時にSQLから取得、push時にSQLに以下のように保存する処理を実装する。
| name:VARCHAR(36)                     | amount:INT | 
| ------------------------------------ | ---------- | 
| 820fb50d-0b0b-b34d-2036-7a6997e89195 | 1000000    | 
| steve's bank                         | 9999999999 |

**Comment by toru-toruto** [comment]
いくつか質問させてください！
・口座っていうのは、プレイヤーが所有する預金を扱うものですか？（例えば、上記の「steve's bank」のsteveはある一人のプレイヤーですか？）
・nameがユニークな値で大丈夫ですか？（steve's bankのような指定の場合、ユニークにならないかも？と思ったり）
・Moneyクラス実装の時、amountをlongで実装しましたがintで十分ですかね？

**Comment by kumitatepazuru** [comment]
> ・口座っていうのは、プレイヤーが所有する預金を扱うものですか？（例えば、上記の「steve's bank」のsteveはある一人のプレイヤーですか？）

そういう認識で大丈夫です。BankクラスのところにUUIDを突っ込んだ場合はUUIDがnameになって、口座名を入れた場合は口座名がnameになる感じです

> ・nameがユニークな値で大丈夫ですか？（steve's bankのような指定の場合、ユニークにならないかも？と思ったり）

ユニークで大丈夫です。逆にユニークにしてくれってくらい。

> ・Moneyクラス実装の時、amountをlongで実装しましたがintで十分ですかね？

intで大丈夫です！

**Comment by toru-toruto** [comment]
口座名も含めてnameをユニークにするとすると、無難なアイデアは
"bank-820fb50d-0b0b-b34d-2036-7a6997e89195"
みたいな"bank-UUID"のような形ですかね？
（でもそうなるとUUIDの指定が必要になる）

**Comment by kumitatepazuru** [comment]
いえ、そのような感じではなくても大丈夫です。ちょっと例が悪かったですね。すみません。
現状考えている方法は
- プレイヤー個人の口座（これはUUIDで保管）
- 誰かとチームを作って何かをする時用の口座（これは固有な名前で保管）

っていう感じになってます。`steave's bank` というのはあくまでも一例でこれは（例えば口座作成者のsteveさんが）招待したプレイヤーは自由に使えるようになる感じです。
（この仕様たちはまた後々造っていく感じで、一旦はSQLに保管する部分のみの実装）

**Comment by toru-toruto** [comment]
すみません、自分が不必要に先のことを考えすぎていると気づきました
一段ずつですね

**Comment by kumitatepazuru** [comment]
そうですね、大きなものをやっちゃうと細かい部分のつめが甘くなってバグとかゲームバランス崩壊の原因になったりするのでissueとかも細かく区切ってやっていくつもりです。（もちろん自分も先のことは考えたいｗ）
そこまで心配することじゃないのでお気になさらず～
