### ISSUE TITLE
GuiクラスとMenuItemのパッケージ

### ISSUE THREAD

**Issue by tererun** [inudevtech/metaverseplugin#23]
パッケージにうるさいおじさんですみません…

GuiクラスもMenuItemもインスタンスを持つものですので、defineパッケージに移動する形でいいかなと思われます…

utilパッケージはインスタンスを持たないstaticな変数やメソッドの集まりのクラスを入れる場所なので、インスタンスを持つものは入れないのが基本かなと思います。

**Comment by kumitatepazuru** [comment]
あぁそうですねｗ
作成を始めたのがdefineに移行する前だったのでそれを移動させるのを忘れてました（）
develop直接pushで大丈夫なので、良ければ移動お願いしたいです（）

**Comment by tererun** [comment]
了解です〜ありがとうございます！

後ほど移動しておきます

**Comment by tererun** [comment]
https://github.com/inudevtech/metaverseplugin/commit/6723b766aafcee367e044c2512b854e3a9bb43ec

移動しました〜

**Comment by kumitatepazuru** [comment]
ありがとうございます～
助かります！
