### ISSUE TITLE
【優先度高】Metazonを作り、アイテムを販売できるようにする

### ISSUE THREAD

**Issue by kumitatepazuru** [inudevtech/metaverseplugin#51]
depends on #32 , #49, #52
Metazonはiphoneから呼び出せるようにする。
名称は一旦仮。
開いたらまず販売するボタンと買うボタンが出るようにする。
今回は販売する機能の実装なので買うボタンは一旦飾りで。
販売ボタンを押したらこういうGUIが出るようにする。統合版もインベントリGUIの表示で。
![image](https://user-images.githubusercontent.com/43287589/172037366-a1b8dc35-d905-4e1a-84ee-294a3a8dde9f.png)
エメラルドは売るときのお金を表す。ここのタイトルにいくらでアイテムを売るかが書かれるようにする。これはあくまでも表示で、実際の取引は現金ではなくシステム上で行われるのでゲーム内通貨を使わわなくてもOK
赤の羊毛は売るときのお金を減らすボタンで、左から-100,-10,-1。
青の羊毛は売るときのお金を増やすボタンで、右から100,10,1。
紙には「下に売りたいアイテムをセットして下さい」みたいなことを書く。クリックしたらアイテムを売れるようにする。
売りたいアイテムは、紙の下の空欄の部分に入れるようにする。
端のエンチャント本は押したらヘルプ( #49 )が出るようにする。
空欄の部分以外はクリックしてもアイテムは取れないようにする。( #52 )
インベントリGUIは、すべてGuiで実装。

**Comment by kumitatepazuru** [comment]
iPhoneに作るという部分に関して。
iPhoneの作成がまだできていないため、一旦はコマンドで呼び出せるようにする。開く関数を用意しておくとiPhoneができてからの移行が楽かも。

**Comment by kumitatepazuru** [comment]
@toru-toruto  #52 をdevelopにmergeしたのでそれをブランチにmergeして使って下さい〜

**Comment by toru-toruto** [comment]
@kumitatepazuru Guiクラスを利用して実装を進めているのですが、2点ほど意図しない挙動が発生しました。
以下の2点がバグであるかお聞きしたいです。
 - Guiクラスを利用して開かれたGUIでは、`Gui#addItem`で追加されたものでないアイテムであってもつかむことができない
 - `Gui#addItem` で、(x, y):(n, 1)の位置に`onClick`を設定した`MenuItem`を追加すると、ホットバー（手持ち）のn番目のスロットにも全く同じ`onClick`イベントが設定されてしまう

**Comment by kumitatepazuru** [comment]
@toru-toruto 連絡ありがとうございます。
1つ目の挙動はもともと`Inventory`に`Gui#addItem`以外でのアイテムを追加することを考えていないので仕様といえば仕様です。（ちなみにGuiで使っているinventoryはprotectedがかかっているはずなのでclassをいじるか継承しなくてはアクセスできないはず）後で警告メッセージを出すように変更をしておきます。
2つ目は完全にバグですね...早急に修正しておきます。

**Comment by kumitatepazuru** [comment]
#66 で修正してdevelopにmergeしました。それをそちらのブランチにmergeして使っていただければ修正されていると思います！

**Comment by toru-toruto** [comment]
爆速な対応ありがとうございます！2つ目の挙動については解決しました。

1つ目の挙動についてですが、まず私の説明不足または説明ミスでした。
`Inventory`に`Gui#addItem`以外の方法でプラグイン側からアイテムを追加したわけではなく、
**もともとプレイヤーが所持していたアイテムがつかめなくなっていた**ということでした。
これについては、2つ目の方のバグ修正(#65)によってつかめるようになりました。

ただ次に、このつかめるようになったプレイヤーのアイテムについて、新たに以下のような挙動が見られるようになりました。
 - つかんだアイテムを、`Gui`を利用して作成されたスロットへ配置しようとしたとき
   - 一度のクリックでは配置できない
   - クリックを連打すると配置できる
 - クリック連打によって配置されたアイテムについて、それを再度つかもうとアイテムをクリックすると、
警告`デベロッパー向け情報: MenuItemに(以下略)` が表示され、アイテムをつかむことはできない
 - クリック連打によって配置されたアイテムは、Metazonの画面を閉じるとそのまま消滅する

これらの挙動にもおそらくバグが含まれていると思いますので、ご対応よろしくお願いしますm(__)m

**Comment by toru-toruto** [comment]
※以下、toru-torutoの希望です

アイテムの配置について私が実現したい動作は以下のような、
要するに**作業台と同様の体験で配置できる**ものです。
- プレイヤーが自身が所持しているアイテムをつかみ、Metazonにおける紙の下の空欄に配置できる
- 空欄に配置されたアイテム（空欄のアイテム）は再度つかむことが可能である
- 所持している他のアイテムをつかみ、空欄のアイテムとつかんでいる他のアイテムを置き替えることも可能である
- 空欄のアイテムはMetazonを閉じた場合、プレイヤー自身のインベントリへ返還される

ただこれらは、実装するならばGuiクラスなのかなと考えてはいます。
基本的にはつかめない仕様にするのであれば、
**つかむことが可能なスロットを明示的に指定できるようにする**のはどうでしょうか？

また仮に、「Guiを利用して作成されたスロットでは、例外なくアイテムをつかむことができない」
という仕様とするならば、上記の作業台と同様の体験はあきらめ、以下のような2つの動作案が考えられます。
- プレイヤー自身のアイテムをつかみ紙の下の空欄に配置することはできるが、
それを再度クリックした場合はつかむことはできず、ワンクリックで自身のインベントリへ返還される
- プレイヤー自身のアイテムもつかむことはできず、
アイテムはワンクリックで空欄への配置・インベントリへの返還が行われる

ただ、前者の場合はプレイヤーにとって違和感のある動作になりそうだなと思います。
また、後者の場合はGuiに「プレイヤーの所持するアイテムであっても一切つかむことはできない」という仕様が必要になってしまうかなと思います。

できれば作業台と同様の体験を実現したいと思っています。
長くなってしまい申し訳ないですが、ご検討よろしくお願いします。

**Comment by kumitatepazuru** [comment]
そうか、アイテムをクリックしても閉じないようにするオプションは作ったけれども移動ができるようにするオプションは作っていませんでした、申し訳ないです。
早速作ってきます。

**Comment by kumitatepazuru** [comment]
#69 で実装しました。MenuItemの最後の引数にDraggableという引数を追加してそれをtrueにすることで動かすことができるようになります。

**Comment by toru-toruto** [comment]
ありがとうございます。助かります！
draggable trueで動かすことができること、確認しました！

また、Metazonを実装するために
こちらの方で、さらに以下のように手を加えようと思うのでその報告です。
- プレイヤーの所持するアイテムを動かすことができるようにする
- DraggableなMenuItemについて、アイテムを設定しないことを許容する
（Metazonの空欄には最初何も入っていないはずなので）

**Comment by toru-toruto** [comment]
@kumitatepazuru 質問させてください。
統合版マイクラで、以下のように統合版GUI（`openA`)とJava版GUI(`openB`)を行き来するコードを実行してみたのですが、Java版GUIから統合版GUIが開きませんでした。
Java版のインベントリを開いている状態では `FloodgatePlayer#sendForm(SimpleForm.Builder)`がうまく動かないのかな？と思うのですが、これを解決するアイデアがもしあればお聞きしたいです。

    public void openA(Player player) {
        Profundus.getInstance().getLogger().info("ほげ");
        Gui gui = new Gui("ほげ");
        gui.addItem(new MenuItem(
                "ほげ",
                (menuItem, player1) -> openB(player)),
                1,
                1);
        gui.open(player, false);
    }

    public void openB(Player player) {
        Profundus.getInstance().getLogger().info("ふが");
        Gui gui = new Gui("ふが");
        gui.addItem(new MenuItem(
                "ふが",
                (menuItem, player1) -> openA(player)),
                1,
                2);
        gui.open(player, true);
    }

**Comment by toru-toruto** [comment]
あっ、今のところできなくてもいいか。
使いやすくなるかと思って「メインメニューへ戻るボタン」を実装しようとしたから必要になったのでした。

ということで、もしできるなら使いたいくらいの気持ちです。

**Comment by kumitatepazuru** [comment]
sendFormはJava版とは違って何かしらのGUIが開いているときは動作しない仕組みになってるのでそうなってるんだと思います。
一応方法は２通りあって、Gui Classにcloseの関数を作ってinventory.close()を入れるか、onclickの処理をSchedulerで1tick間を空けて遅延で処理をさせるですかね....

**Comment by kumitatepazuru** [comment]
あ、あとはhttps://github.com/inudevtech/Profundus/blob/develop/src/main/java/tech/inudev/profundus/define/Gui.java#L196-L201　　 ここのコードのif文の順序を逆にしても行けるかもです

**Comment by toru-toruto** [comment]
なんか...Schedulerで2tick遅らせたら動きました...
閉じてる途中も受け付けないのかしら...？

**Comment by kumitatepazuru** [comment]
かもしれないｗ
if文逆にしたら1tickでも行けるのかも...?

**Comment by toru-toruto** [comment]
if文は逆にしてやってそれでした。

まあ、インベントリが閉じるのもtickの上で動くなら、2tick遅延の実装で問題ないんですかね...？

**Comment by kumitatepazuru** [comment]
なんかもやっとするけどまぁいいやｗ
動いたらいいだろ精神で行きましょうｗ（良くないけど）

**Comment by toru-toruto** [comment]
よし！（バグの素として覚えておきます）
