### ISSUE TITLE
`HelpUtil`に関して、`initializeHelp`時にenumを渡してプラグイン毎に読み込むファイルを変えられるようにしたい。

### ISSUE THREAD

**Issue by kumitatepazuru** [inudevtech/metaverseplugin#94]
`HelpUtil`に関して、`initializeHelp`時にenumを渡してプラグイン毎に読み込むファイルを変えられるようにしたい。
これはまた別issueにして処理する

_Originally posted by @kumitatepazuru in https://github.com/Profundus-inudev/Profundus/issues/93#issuecomment-1196567953_

**Comment by kumitatepazuru** [comment]
@toru-toruto ちょうどとるとさんがFreeっぽいのでやっていただきたいのですが大丈夫ですか？

**Comment by toru-toruto** [comment]
大丈夫です！
